## Core Service Credit Balance

In [1]:
## Let's start at the beginning and import the libraries and reading the data
import pandas as pd
df_core = pd.read_csv('balance_core_services.csv')

In [2]:
## As always lets look at the data in order to make sure everything is ok
df_core.head(15)

,Studio Name,Day of Issue Date,Day of Expire Date,Client ID,Full Name,Email,Phone #,Business Category,Credit Source,Credit Description,Initial Credit Count,Used Credit Count,Remaining Credits,Index,Max date
0,"Pinecrest, FL","January 29, 2022","December 30, 2023",425256,Carlos - Musso,cmusso@unisa.com,3056069800,Core Services,Package,MB Migration,9,0,9,1,1/4/2024
1,"Pinecrest, FL","December 23, 2022","May 5, 2024",778692,Eduardo - Suarez,irisysuarez@gmail.com,3052194709,Core Services,Package,MB Migration,2,0,2,2,1/4/2024
2,"Pinecrest, FL","February 9, 2023","June 22, 2024",893506,Philippe - Mathelier,alexmathe1@yahoo.com,17862866516,Core Services,Package,MB Migration,3,0,3,3,1/4/2024
3,"Pinecrest, FL","May 19, 2023","December 4, 2023",14307,George - Savage,gss@savagelaw.net,3054913182,Core Services,Package,MB Migration,6,0,6,4,1/4/2024
4,"Pinecrest, FL","May 19, 2023","December 4, 2023",122648,Randi - Shannon,randishannon@gmail.com,3054914597,Core Services,Package,MB Migration,6,0,6,5,1/4/2024
5,"Pinecrest, FL","May 19, 2023","December 4, 2023",219037,Javier - Rodriguez,javy@lucaelite.com,3058077096,Core Services,Package,MB Migration,8,0,8,6,1/4/2024
6,"Pinecrest, FL","May 19, 2023","December 4, 2023",658521,Michael - Aguirre,mikeeaguirre@gmail.com,3054942156,Core Services,Package,MB Migration,8,0,8,7,1/4/2024
7,"Pinecrest, FL","May 20, 2023","December 5, 2023",495794,Alex - Ruiz,alexjrca@gmail.com,3107457498,Core Services,Package,MB Migration,7,0,7,8,1/4/2024
8,"Pinecrest, FL","May 20, 2023","December 5, 2023",958000,Lewis - Pickett,lewispickett@gmail.com,14017936699,Core Services,Package,MB Migration,2,0,2,9,1/4/2024
9,"Pinecrest, FL","May 20, 2023","December 5, 2023",973252,Blase - Cunningham,blasecastor@yahoo.com,7869229304,Core Services,Package,MB Migration,7,0,7,10,1/4/2024
10,"Pinecrest, FL","May 20, 2023","December 5, 2023",973253,Mia - Cunningham,mia.barcelona.2008@gmail.com,19143145045,Core Services,Package,MB Migration,7,0,7,11,1/4/2024
11,"Pinecrest, FL","May 21, 2023","December 6, 2023",965514,Marco - Chirico,marco.chirico@gmail.com,14083269837,Core Services,Package,MB Migration,3,0,3,12,1/4/2024
12,"Pinecrest, FL","May 24, 2023","December 9, 2023",976629,Anthony - Fernandez,antxf2122@gmail.com,17867697000,Core Services,Package,MB Migration,2,0,2,13,1/4/2024
13,"Pinecrest, FL","May 25, 2023","December 10, 2023",868184,Zachary - Schneider,zschneider@mail.usf.edu,3058030957,Core Services,Package,MB Migration,6,0,6,14,1/4/2024
14,"Pinecrest, FL","May 25, 2023","December 10, 2023",917199,Evelyn - Fernandez,evelynkw20@gmail.com,7868240988,Core Services,Package,MB Migration,9,0,9,15,1/4/2024

In [3]:
## Now we can get rid of columns that we don't need and redefine the variable
## As you can see we will also be getting rid of the initial credit count. Explained later
df_core = df_core.drop(columns=['Studio Name', 'Day of Issue Date', 'Day of Expire Date', 'Client ID', 'Business Category', 'Credit Source', 'Initial Credit Count', 'Used Credit Count', 'Index', 'Max date'])

## Printing
df_core

,Full Name,Email,Phone #,Credit Description,Remaining Credits
0,Carlos - Musso,cmusso@unisa.com,3056069800,MB Migration,9
1,Eduardo - Suarez,irisysuarez@gmail.com,3052194709,MB Migration,2
2,Philippe - Mathelier,alexmathe1@yahoo.com,17862866516,MB Migration,3
3,George - Savage,gss@savagelaw.net,3054913182,MB Migration,6
4,Randi - Shannon,randishannon@gmail.com,3054914597,MB Migration,6
...,...,...,...,...,...
152,Roberto - Fernandez,rescuebob505@gmail.com,3052823568,Core Credit,1
153,Josh - Schiffrin,jschiff29@aol.com,3057996400,Core Service | 3 Pack,2
154,Lisa - Perez,miamiliza305@gmail.com,3056150534,Core Service | 3 Pack,2
155,Michelle - Perez,meechp1130@gmail.com,3052838888,Core Service | 3 Pack,2
156,Michelle - Perez,meechp1130@gmail.com,3052838888,Core Service | 3 Pack,1

In [4]:
## We'll also rename the columns to make them easily usable and redefine the varible
df_core = df_core.rename(columns={'Full Name': 'full_name'})
df_core = df_core.rename(columns={'Phone #': 'phone'})
df_core = df_core.rename(columns={'Credit Description': 'credit_description'})
df_core = df_core.rename(columns={'Remaining Credits': 'remaining_credits'})

## Printing
df_core

,full_name,Email,phone,credit_description,remaining_credits
0,Carlos - Musso,cmusso@unisa.com,3056069800,MB Migration,9
1,Eduardo - Suarez,irisysuarez@gmail.com,3052194709,MB Migration,2
2,Philippe - Mathelier,alexmathe1@yahoo.com,17862866516,MB Migration,3
3,George - Savage,gss@savagelaw.net,3054913182,MB Migration,6
4,Randi - Shannon,randishannon@gmail.com,3054914597,MB Migration,6
...,...,...,...,...,...
152,Roberto - Fernandez,rescuebob505@gmail.com,3052823568,Core Credit,1
153,Josh - Schiffrin,jschiff29@aol.com,3057996400,Core Service | 3 Pack,2
154,Lisa - Perez,miamiliza305@gmail.com,3056150534,Core Service | 3 Pack,2
155,Michelle - Perez,meechp1130@gmail.com,3052838888,Core Service | 3 Pack,2
156,Michelle - Perez,meechp1130@gmail.com,3052838888,Core Service | 3 Pack,1

<font size="5">Working with bad data</font>

In [5]:
## We need to get the initial credits in an integer in order to perform calculations
## Since we are wokring with data that does not give us the init
df_core['initial_credits'] = df_core['credit_description'].astype(str).str.extract(r'(\d+)', expand=False)

## Printing
df_core

,full_name,Email,phone,credit_description,remaining_credits,initial_credits
0,Carlos - Musso,cmusso@unisa.com,3056069800,MB Migration,9,NaN
1,Eduardo - Suarez,irisysuarez@gmail.com,3052194709,MB Migration,2,NaN
2,Philippe - Mathelier,alexmathe1@yahoo.com,17862866516,MB Migration,3,NaN
3,George - Savage,gss@savagelaw.net,3054913182,MB Migration,6,NaN
4,Randi - Shannon,randishannon@gmail.com,3054914597,MB Migration,6,NaN
...,...,...,...,...,...,...
152,Roberto - Fernandez,rescuebob505@gmail.com,3052823568,Core Credit,1,NaN
153,Josh - Schiffrin,jschiff29@aol.com,3057996400,Core Service | 3 Pack,2,3
154,Lisa - Perez,miamiliza305@gmail.com,3056150534,Core Service | 3 Pack,2,3
155,Michelle - Perez,meechp1130@gmail.com,3052838888,Core Service | 3 Pack,2,3
156,Michelle - Perez,meechp1130@gmail.com,3052838888,Core Service | 3 Pack,1,3

In [6]:
## There are some core credits that are named "Core Credit." We don't need that one because they don't have integers for us to perform calculations
## Since we created the initial credits list, we can see that the ones with 'core credit' description gives us NaN
## This is perfect because now we can use the dropna() function to go ahead and get rid of those rows 
df_core = df_core.dropna()

## Printing
df_core

,full_name,Email,phone,credit_description,remaining_credits,initial_credits
23,Michelle - Doyle,girlpower264@gmail.com,3052137631,Core Service | 3 Pack,3,3
24,Andres - Silveira,specmed1@bellsouth.net,7862532884,Core Service | 10 Pack,10,10
26,Valeria - Arias-Ferro,valeria_arias_esq@yahoo.com,3052058890,Core Service | 10 Pack,10,10
27,Daniel - Acevedo,crnadanny@gmail.com,3059844648,Core Service | 3 Pack,3,3
28,Lisa - Sloane,sloanenaples@aol.com,7863741041,Core Service | 3 Pack,1,3
...,...,...,...,...,...,...
150,Aurelio - Valle,changethisemail@gmail.com,9174741379,Core Service | 3 Pack,3,3
153,Josh - Schiffrin,jschiff29@aol.com,3057996400,Core Service | 3 Pack,2,3
154,Lisa - Perez,miamiliza305@gmail.com,3056150534,Core Service | 3 Pack,2,3
155,Michelle - Perez,meechp1130@gmail.com,3052838888,Core Service | 3 Pack,2,3
156,Michelle - Perez,meechp1130@gmail.com,3052838888,Core Service | 3 Pack,1,3

In [7]:
## If we tried to iterrate through the rows and do our calculations, it wont work
## Let's see why it won't
df_core.dtypes

full_name             object
Email                 object
phone                  int64
credit_description    object
remaining_credits      int64
initial_credits       object
dtype: object

In [8]:
## As you can see, the new initial credits is seen as an object
## We can change this by turning it into a string type and then an integer
df_core['initial_credits'] = df_core['initial_credits'].astype(str).astype(int)

## Now let's check
df_core.dtypes

C:\Users\jason\AppData\Local\Temp\ipykernel_20144\3452177653.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_core['initial_credits'] = df_core['initial_credits'].astype(str).astype(int)

full_name             object
Email                 object
phone                  int64
credit_description    object
remaining_credits      int64
initial_credits        int32
dtype: object

In [9]:
## Let start performing calculations
core_list = []

for index, row in df_core.iterrows():
    remaining = row['remaining_credits']
    initial = row['initial_credits']
    calculated_percentage = (remaining / initial) * 100
    utilization = 100 - calculated_percentage
    if utilization > 60:
        my_list = [row.full_name, row.phone, row.credit_description, row.remaining_credits]
        core_list.append(my_list)

## Printing
core_list

[['Lisa - Sloane', 7863741041, 'Core Service | 3 Pack', 1],
 ['Elizabeth - Guaico', 13054095422, 'Core Service | 3 Pack', 1],
 ['Amy - Brannon', 3052987333, 'Core Service | 3 Pack', 1],
 ['Ariel - Guanoluisa', 7863651958, 'Core Service | 3 Pack', 1],
 ['Paul - Sotolongo', 7869705774, 'Core Service | 3 Pack', 1],
 ['Katherine - Ramos', 3057481733, 'Core Service | 3 Pack', 1],
 ['Abby - Martinez', 7863197591, 'Core Service | 3 Pack', 1],
 ['Raul - Marcano', 3059925865, 'Core Service | 3 Pack', 1],
 ['Todd - Hochstadt', 3106634466, 'Core Service | 3 Pack', 1],
 ['Mark - Perez', 8183178899, 'Core Service | 5 Pack', 1],
 ['Jimmi - Chaplin', 7049956320, 'Core Service | 3 Pack', 1],
 ['Lucas - Goenaga', 3059656976, 'Core Service | 3 Pack', 1],
 ['CHIQUI - DELGADO', 7864737664, 'Core Service | 3 Pack', 1],
 ['Roxanne - Rissing', 6784811389, 'Core Service | 3 Pack', 1],
 ['Mael - Garcia', 7863940770, 'Core Service | 3 Pack', 1],
 ['Julio - Rodriguez', 7862002928, 'Core Service | 3 Pack', 1],
 ['Lyn - Gonzalez', 7865275443, 'Core Service | 3 Pack', 1],
 ['Carlos - Sluman', 7875019919, 'Core Service | 10 Pack', 3],
 ['Erick - Percy', 9548509617, 'Core Service | 3 Pack', 1],
 ['John - Culbertson', 13059684707, 'Core Service | 3 Pack', 1],
 ['Pedro - Chavez', 3052441540, 'Core Service | 3 Pack', 1],
 ['Christina - Mahoney', 5408346840, 'Core Service | 3 Pack', 1],
 ['Yuehan - Zhao', 13054849054, 'Core Service | 3 Pack', 1],
 ['Rhonda - Castillo', 7868791044, 'Core Service | 3 Pack', 1],
 ['Jacob - Gonzalez', 3055252960, 'Core Service | 3 Pack', 1],
 ['Yamir - Laboy', 3057724513, 'Core Service | 3 Pack', 1],
 ['Diego - Ayala', 7868620675, 'Core Service | 3 Pack', 1],
 ['Kalyn - Gibbs', 7867805433, 'Core Service | 3 Pack', 1],
 ['Justin - Guzzo', 3058035706, 'Core Service | 3 Pack', 1],
 ['Angel - Sajous', 3057983939, 'Core Service | 3 Pack', 1],
 ['Landy - Labadie', 3053974473, 'Core Service | 3 Pack', 1],
 ['Jennifer - Kanold', 7866507701, 'Core Service | 3 Pack', 1],
 ['Hannah - Hartley', 3052979110, 'Core Service | 3 Pack', 1],
 ['Iraida - Garcia', 3052447536, 'Core Service | 3 Pack', 1],
 ['Alain - Piloto-Rios', 5024359577, 'Core Service | 3 Pack', 1],
 ['Marchetti - Anthoney', 4108049688, 'Core Service | 3 Pack', 1],
 ['Jennifer - Linares', 3053890464, 'Core Service | 3 Pack', 1],
 ['Christian - Bridges', 7862986914, 'Core Service | 3 Pack', 1],
 ['yanisset - urra', 7868180630, 'Core Service | 3 Pack', 1],
 ['Michelle - Perez', 3052838888, 'Core Service | 3 Pack', 1]]

## Making the List actionable

In [10]:
## Now that we have the list, let's turn it into a dataframe
core_list_df = pd.DataFrame(core_list, columns=['Full Name', 'Phone Number', 'Credit Description', 'Remaining Credits'])

## Printing
core_list_df

,Full Name,Phone Number,Credit Description,Remaining Credits
0,Lisa - Sloane,7863741041,Core Service | 3 Pack,1
1,Elizabeth - Guaico,13054095422,Core Service | 3 Pack,1
2,Amy - Brannon,3052987333,Core Service | 3 Pack,1
3,Ariel - Guanoluisa,7863651958,Core Service | 3 Pack,1
4,Paul - Sotolongo,7869705774,Core Service | 3 Pack,1
5,Katherine - Ramos,3057481733,Core Service | 3 Pack,1
6,Abby - Martinez,7863197591,Core Service | 3 Pack,1
7,Raul - Marcano,3059925865,Core Service | 3 Pack,1
8,Todd - Hochstadt,3106634466,Core Service | 3 Pack,1
9,Mark - Perez,8183178899,Core Service | 5 Pack,1
10,Jimmi - Chaplin,7049956320,Core Service | 3 Pack,1
11,Lucas - Goenaga,3059656976,Core Service | 3 Pack,1
12,CHIQUI - DELGADO,7864737664,Core Service | 3 Pack,1
13,Roxanne - Rissing,6784811389,Core Service | 3 Pack,1
14,Mael - Garcia,7863940770,Core Service | 3 Pack,1
15,Julio - Rodriguez,7862002928,Core Service | 3 Pack,1
16,Lyn - Gonzalez,7865275443,Core Service | 3 Pack,1
17,Carlos - Sluman,7875019919,Core Service | 10 Pack,3
18,Erick - Percy,9548509617,Core Service | 3 Pack,1
19,John - Culbertson,13059684707,Core Service | 3 Pack,1
20,Pedro - Chavez,3052441540,Core Service | 3 Pack,1
21,Christina - Mahoney,5408346840,Core Service | 3 Pack,1
22,Yuehan - Zhao,13054849054,Core Service | 3 Pack,1
23,Rhonda - Castillo,7868791044,Core Service | 3 Pack,1
24,Jacob - Gonzalez,3055252960,Core Service | 3 Pack,1
25,Yamir - Laboy,3057724513,Core Service | 3 Pack,1
26,Diego - Ayala,7868620675,Core Service | 3 Pack,1
27,Kalyn - Gibbs,7867805433,Core Service | 3 Pack,1
28,Justin - Guzzo,3058035706,Core Service | 3 Pack,1
29,Angel - Sajous,3057983939,Core Service | 3 Pack,1
30,Landy - Labadie,3053974473,Core Service | 3 Pack,1
31,Jennifer - Kanold,7866507701,Core Service | 3 Pack,1
32,Hannah - Hartley,3052979110,Core Service | 3 Pack,1
33,Iraida - Garcia,3052447536,Core Service | 3 Pack,1
34,Alain - Piloto-Rios,5024359577,Core Service | 3 Pack,1
35,Marchetti - Anthoney,4108049688,Core Service | 3 Pack,1
36,Jennifer - Linares,3053890464,Core Service | 3 Pack,1
37,Christian - Bridges,7862986914,Core Service | 3 Pack,1
38,yanisset - urra,7868180630,Core Service | 3 Pack,1
39,Michelle - Perez,3052838888,Core Service | 3 Pack,1

In [17]:
## Since that looks good, we can turn that into an excel sheet and send it to the reps
core_list_df.to_excel('Remaining Core Credits.xlsx')